experimentalOperatorPosition: start
experimentalTernaries: true
objectWrap: collapse
proseWrap: always
quoteProps: consistent
singleQuote: true

plugins:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-sort-json
  - prettier-plugin-pkg

# ------------------------------------------------------------------------------
# @ianvs/prettier-plugin-sort-imports

importOrder:
  - ''
  - <TYPES>^(node:)
  - <TYPES>
  - <BUILTIN_MODULES>
  - ''
  - <THIRD_PARTY_MODULES>
  - ''
  - <TYPES>^[.]
  - ^(@api|@assets|@ui)(/.*)$
  - ^[.]

importOrderCaseSensitive: false

# ------------------------------------------------------------------------------
# prettier-plugin-sort-json

jsonRecursiveSort: true
jsonSortOrder: '{"*": "caseInsensitiveNumeric"}'

# ------------------------------------------------------------------------------
# Overrides

overrides:
  - files: .vscode/*.json
    options:
      parser: jsonc
  - files: LICENSE
    options:
      parser: markdown
